### ISSUE TITLE
docker compose windows vs linux (invalid fields)

### ISSUE THREAD

**Issue by tmavroeid** [typhon-project/typhondl#13]
docker-compose-windows:
```
version: '3.7'
services:
  polystore_api:
    image: clms/typhon-polystore-api:latest
    depends_on: 
      - polystoredb
    container_name: typhon-polystore-service
    restart: always
    hostname: polystore-api
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
  polystore_ui:
    image: clms/typhon-polystore-ui:latest
    environment:
      APIPORT: 8080
    depends_on: 
      - polystore_api
    container_name: polystore-ui
    ports:
      - 4200:4200
    restart: always
    hostname: polystore-ui
  polystoredb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: polystore-mongo
    hostname: polystore-api-db
    ports:
      - 27017:27017
```

docker-compose-linux:
```
version: '3.7'
services:
  polystore_api:
    image: invalid
    depends_on: 
      - polystoredb
    invalid: invalid
    ports:
      - invalid
    volumes:
      - invalid
  polystore_ui:
    image: invalid
    depends_on: 
      - polystore_api
    invalid: invalid
    ports:
      - invalid
  polystoredb:
    image: invalid
    invalid: invalid
    ports:
      - invalid
```
