### ISSUE TITLE
[Feature] Limit API's and QL's memory usage in TyphonDL Creation Wizard

### ISSUE THREAD

**Issue by MarieSaphira** [typhon-project/typhondl#64]
**Is your feature request related to a problem? Please describe.**
Components use too much memory

**Describe the solution you'd like**
Define resource reservations and limits for the Polystore API and QL in the TyphonDL Creation Wizard

**Describe alternatives you've considered**
Directly adding resource limitations to the generated kubernetes script. E.g.
```
      containers:
        - name: typhon-polystore-service-container
          image: clms/typhon-polystore-api:latest
          ports:
            - containerPort: 8080 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
```
