### ISSUE TITLE
[Feature] add volume mount for `polystore-mongo`

### ISSUE THREAD

**Issue by DavyLandman** [typhon-project/typhondl#78]
**Is your feature request related to a problem? Please describe.**
You don't want to restart the container and have lost your updated models.

**Describe the solution you'd like**
Add a default volume to the `polystore-mongo` container just like the user database containers get.

**Describe alternatives you've considered**
Re upload the models everytime after re-up?

**Additional context**
Currently it generates:

```
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
```
